
package org.egitimdemoejb.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EgitimDemoWSService", targetNamespace = "http://ws.EgitimDemoEjb.org/", wsdlLocation = "http://localhost:8080/EgitimDemoWeb/webservices/EgitimDemoWS?wsdl")
public class EgitimDemoWSService
    extends Service
{

    private final static URL EGITIMDEMOWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.egitimdemoejb.ws.EgitimDemoWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.egitimdemoejb.ws.EgitimDemoWSService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/EgitimDemoWeb/webservices/EgitimDemoWS?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/EgitimDemoWeb/webservices/EgitimDemoWS?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EGITIMDEMOWSSERVICE_WSDL_LOCATION = url;
    }

    public EgitimDemoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EgitimDemoWSService() {
        super(EGITIMDEMOWSSERVICE_WSDL_LOCATION, new QName("http://ws.EgitimDemoEjb.org/", "EgitimDemoWSService"));
    }

    /**
     * 
     * @return
     *     returns EgitimDemoWS
     */
    @WebEndpoint(name = "EgitimDemoWSPort")
    public EgitimDemoWS getEgitimDemoWSPort() {
        return super.getPort(new QName("http://ws.EgitimDemoEjb.org/", "EgitimDemoWSPort"), EgitimDemoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EgitimDemoWS
     */
    @WebEndpoint(name = "EgitimDemoWSPort")
    public EgitimDemoWS getEgitimDemoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.EgitimDemoEjb.org/", "EgitimDemoWSPort"), EgitimDemoWS.class, features);
    }

}
