
package org.egitimdemoejb.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EgitimDemoWS", targetNamespace = "http://ws.EgitimDemoEjb.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EgitimDemoWS {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeStudent", targetNamespace = "http://ws.EgitimDemoEjb.org/", className = "org.egitimdemoejb.ws.RemoveStudent")
    @ResponseWrapper(localName = "removeStudentResponse", targetNamespace = "http://ws.EgitimDemoEjb.org/", className = "org.egitimdemoejb.ws.RemoveStudentResponse")
    public void removeStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        Student arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://ws.EgitimDemoEjb.org/", className = "org.egitimdemoejb.ws.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://ws.EgitimDemoEjb.org/", className = "org.egitimdemoejb.ws.AddStudentResponse")
    public void addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        Student arg0);

    /**
     * 
     * @return
     *     returns java.util.List<org.egitimdemoejb.ws.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudents", targetNamespace = "http://ws.EgitimDemoEjb.org/", className = "org.egitimdemoejb.ws.GetStudents")
    @ResponseWrapper(localName = "getStudentsResponse", targetNamespace = "http://ws.EgitimDemoEjb.org/", className = "org.egitimdemoejb.ws.GetStudentsResponse")
    public List<Student> getStudents();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.egitimdemoejb.ws.County>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCounties", targetNamespace = "http://ws.EgitimDemoEjb.org/", className = "org.egitimdemoejb.ws.GetCounties")
    @ResponseWrapper(localName = "getCountiesResponse", targetNamespace = "http://ws.EgitimDemoEjb.org/", className = "org.egitimdemoejb.ws.GetCountiesResponse")
    public List<County> getCounties(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<org.egitimdemoejb.ws.Gender>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGenders", targetNamespace = "http://ws.EgitimDemoEjb.org/", className = "org.egitimdemoejb.ws.GetGenders")
    @ResponseWrapper(localName = "getGendersResponse", targetNamespace = "http://ws.EgitimDemoEjb.org/", className = "org.egitimdemoejb.ws.GetGendersResponse")
    public List<Gender> getGenders();

    /**
     * 
     * @return
     *     returns java.util.List<org.egitimdemoejb.ws.City>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCities", targetNamespace = "http://ws.EgitimDemoEjb.org/", className = "org.egitimdemoejb.ws.GetCities")
    @ResponseWrapper(localName = "getCitiesResponse", targetNamespace = "http://ws.EgitimDemoEjb.org/", className = "org.egitimdemoejb.ws.GetCitiesResponse")
    public List<City> getCities();

}
